### ISSUE TITLE
sending base64 encoded password on the login form

### ISSUE THREAD

**Issue by YiannisGkoufas** [nielsutrecht/jwt-angular-spring#7]
Hi there,

it's not an issue rather than a question.
What changes would it need to also send the password on the login form?
I am guessing it has to be encoded and also the rest controller to parse it appropriately right?

Thanks!

**Comment by nielsutrecht** [comment]
Hi Yiannis,

That is correct. I left out the password in this example because it's not needed to showcase how a JWT would work. So you would indeed need to also send a password alongside the username with the request. A few things to take into account:

- Make sure you use HTTPS in production; without it passwords will be plain text in transit.
- Make sure you use a strong password hash like Bcrypt, Scrypt or PBKDF2 to store password hashes in your database. Never store it in plaintext and never use fast hashes like MD5 or SHA to hash passwords. Especially MD5 is completely broken.

Kind regards,

Niels
